name: visa-process-workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '35 0 * * *'

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipelines
        env:
          API_KEY: ${{ secrets.VISA_API_KEY }}
        run: python sample.py

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-name"
          git add .          
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "Automated data pipeline run"
          git push

